# Generated by Django 5.2.4 on 2025-08-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='first_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
